### ISSUE TITLE
Error Creating the Jupyter Interactive Widget

### ISSUE THREAD

**Issue by JustinChavez** [aernesto/dots-reversal-ideal-obs#1]
I tried running the jupyter notebook, but I keep getting the following error which prevents me from interacting with the widget:

![image](https://user-images.githubusercontent.com/8655231/29991371-b225b98e-8f53-11e7-92bb-5e2d25795b13.png)

I was sure to run all the cells before this cell. Do you think it may be a package I have not downloaded?

I am running Python 3.6.2

**Comment by aernesto** [comment]
@JustinChavez 
Have you tried what they describe here?
https://github.com/jupyter-widgets/ipywidgets/issues/541

**Comment by JustinChavez** [comment]
I have resolved the issue. I did not have the ipywidgets package and installed it through this link: http://ipywidgets.readthedocs.io/en/latest/user_install.html
