### ISSUE TITLE
Can't create environment on Linux because of appnope

### ISSUE THREAD

**Issue by aernesto** [aernesto/dots-reversal-ideal-obs#3]
Hi @JustinChavez,
I am trying to follow your README.md instructions to create the environment. I am encountering the issue described [there](https://github.com/mortonjt/workflow-manager-playground/issues/1#issuecomment-332028094).  
By looking [here](https://groups.google.com/forum/#!topic/neon-users/a3DmW8CPzhE), it seems that appnope is an OS X only package...

Removing appnope from the environment.yml file seems to work. Will this generate any problems down the line?

**Comment by JustinChavez** [comment]
Hi @aernesto 

I am sorry you had to deal with that problem. I totally forgot to look into if any of my OSX packages might conflict with your Linux environment. 

I looked into the problem and removing appnope was the right move. It should not generate any problems down the line as it was created to deal with a problem that is only relevant to OSX operating systems. 

I will create two environment.yml files now. One for osx machines and one for linux machines so future users will not encounter this problem. Look out for this in a future push.
