### ISSUE TITLE
.yaml or .yml file?

### ISSUE THREAD

**Issue by aernesto** [aernesto/dots-reversal-ideal-obs#4]
Hi @JustinChavez,
the file in the repo has a `.yml` extension but the suggested command has a `.yaml` extension. Where is the typo?

**Comment by JustinChavez** [comment]
This is a new issue. [The documentation from anaconda uses .yml](https://conda.io/docs/user-guide/tasks/manage-environments.html). 

Is it conda that is asking you to use .yaml? Is it preventing you from using .yml?

Officially this is from a more broader debate of whether one should use .yml or .yaml. Each repository maintainer has their own preference and might ask/force you to follow it. It is just a naming convention the community is fragmented upon. Kinda like the tabs vs spaces debate. [More information](https://stackoverflow.com/questions/22268952/what-is-the-difference-between-yaml-vs-yml-extension)

**Comment by JustinChavez** [comment]
Oh my. I just realized that it was my suggestion in the README.md to use .yaml. That should read .yml. 

Thanks for catching that! I changed it to .yml. Please ignore my questions in my previous response.
